### ISSUE TITLE
Windows Blen-4.2 "render lipsync" error

### ISSUE THREAD

**Issue by weThere** [blackears/parrotLipsync#11]
Initially had the same issue as Sim1603 in #10. 

Albeit it was for "gruut not found" instead. 

Running 4.2 as admin and reinstalling breached that hurdle, but now rendering sees no success:

<img width="673" alt="Screenshot 2024-08-31 163841" src="https://github.com/user-attachments/assets/de87eb7e-2d2d-4980-98ca-97e05c0748cb">

Specifically confirmed the presence of babel by:
`C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\bin>python.exe -m pip install babel Requirement already satisfied: babel in c:\users\xxxx\appdata\roaming\python\python311\site-packages (2.15.0)`

At the time this leaves me confused.

Expanded trace from internal blender terminal:

```
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\parrotLipsync\parrot_lipsync.py", line 877, in execute
    render_lipsync_to_action(context, tgt_action, seq)
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\parrotLipsync\parrot_lipsync.py", line 526, in render_lipsync_to_action
    word_list_info, phoneme_word_list, sound_profile = get_phonemes_from_file(context, seq)
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\parrotLipsync\parrot_lipsync.py", line 382, in get_phonemes_from_file
    from gruut import sentences
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\site-packages\gruut\__init__.py", line 11, in <module>
    from gruut.const import KNOWN_LANGS, TextProcessorSettings
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\site-packages\gruut\const.py", line 12, in <module>
    import babel
ModuleNotFoundError: No module named 'babel'
Error: Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\site-packages\gruut\__init__.py", line 11, in <module>
    from gruut.const import KNOWN_LANGS, TextProcessorSettings
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\site-packages\gruut\const.py", line 12, in <module>
    import babel
ModuleNotFoundError: No module named 'babel'
Error in bpy.app.handlers.depsgraph_update_post[5]:
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\keyframe_tools_extension\__init__.py", line 153, in update_constraints_fcurves
    scene.keymapframe_maker.anime_fcurves_props.update_active_fcurves(bpy.context)
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\keyframe_tools_extension\__init__.py", line 52, in update_active_fcurves
    for fcurve in obj.animation_data.action.fcurves:
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'fcurves'
Warning: add-on missing 'bl_info', this can cause poor performance!: 'C:\\Users\\xxxx\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\scripts\\addons\\auto_rig_datas.py'
Warning: add-on missing 'bl_info', this can cause poor performance!: 'C:\\Users\\xxxx\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\scripts\\addons\\jrt_remesh_op.py'
Warning: add-on missing 'bl_info', this can cause poor performance!: 'C:\\Users\\xxxx\\AppData\\Roaming\\Blender Foundation\\Blender\\4.2\\scripts\\addons\\rig_prefs.py'
Error in bpy.app.handlers.depsgraph_update_post[5]:
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\keyframe_tools_extension\__init__.py", line 153, in update_constraints_fcurves
    scene.keymapframe_maker.anime_fcurves_props.update_active_fcurves(bpy.context)
  File "C:\Users\xxxx\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org\keyframe_tools_extension\__init__.py", line 52, in update_active_fcurves
    for fcurve in obj.animation_data.action.fcurves:
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'fcurves'
```

I've not really coded in a long time due to circumstance, any further troubleshoot from here is hopefully more intuitive for you, unless it builds on the issue laid out further in #10 about module handling in 4.2.

The silver lining at least is that it works for Blender 4.1 as it did for Sim1603.

**Comment by blackears** [comment]
Blender made big changes to how addons are managed in 4.2.  Before you could install extra libraries by using the pip installer, but that no longer works.  Blender wants you to bundle the libraries as part of the addon now using wheels, but when I tried doing that, I got other errors.  I'm still trying to work out how to rework the addon installer so that I can ship the libraries and have them work in 4.2.

**Comment by blackears** [comment]
I've pushed a new release that should work with Blender 4.2  Please let me know if it works for you.

**Comment by blackears** [comment]
Closing in favor of https://github.com/blackears/parrotLipsync/issues/10

**Comment by weThere** [comment]
It works swimmingly from what I've used it for now. Noticed the scale action to sound wave amplitude is omitted, haven't directly tested it, but it seems like an implicit function now?

**Comment by blackears** [comment]
I removed it from the 1.1.o update since most of the advice I got was that lipsyncing depended more on the frequency of syllables than the size of the mouth poses.  It also made the code significantly simpler.
